EMULATOR_LOCATION = "emulator\\visualboyadvance-m.exe"
EMULATOR_NAME = "VisualBoyAdvance-M 2.1.4"
EMULATOR_NAME_RUNNING = "blue - VisualBoyAdvance-M 2.1.4"
ROM_NAME = "blue.zip"

EMULATOR_BOOT_DELAY = 2
CINEMATIC_DELAY = False

SCREEN_SHOT_Y_REMOVAL = 45
SCREEN_SHOT_INTERVAL = 30.0
